version: "3"

services:
  app:
    build:
      context: .
      dockerfile: scripts/docker/app/Dockerfile
    expose:
      - 8080
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "8080:8080"

  db:
    build:
      context: .
      dockerfile: scripts/docker/db/Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust